In [1]:
import numpy as np

In [5]:
data1 = [1,2,3,4,5]


arr1 = np.array(data1)
print(arr1)
print(arr1.shape)
print(arr1.dtype)

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(arr1.shape)
print(arr1.dtype)

arr1 = np.array([1.0,2.0,3.0,4.0,5.0])
print(arr1)
print(arr1.shape)
print(arr1.dtype)

arr2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr2)
print(arr2.shape)
print(arr2.dtype)

[1 2 3 4 5]
(5,)
int32
[1 2 3 4 5]
(5,)
int32
[1. 2. 3. 4. 5.]
(5,)
float64
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
int32


__numpy shape__  
numpy에서는 해당 array의 크기를 알 수 있다.
shape 을 확인함으로써 몇개의 데이터가 있는지, 몇 차원으로 존재하는지 등을 확인할 수 있다.
위에서 arr1.shape의 결과는 (5,) 으로써, 1차원의 데이터이며 총 5라는 크기를 갖고 있음을 알 수 있다.
arr1.shape의 결과는 (4,3) 으로써, 2차원의 데이터이며 4 * 3 크기를 갖고 있는 array 이다.  


__numpy 자료형__
첫번재나 두번째 arr1는 int32라는 자료형을 갖는 것에 반해 세번째 arr1는 float64라는 자료형을 갖는다.
이는 내부 데이터를 살펴보면 __3.0 5.0 이라는 실수형 데이터__ 를 갖기 때문임을 알 수 있다.
numpy에서 사용되는 자료형은 아래와 같다. (자료형 뒤에 붙는 숫자는 몇 비트 크기인지를 의미한다.)

- 부호가 있는 정수 int(8, 16, 32, 64)
- 부호가 없는 정수 uint(8 ,16, 32, 54)
- 실수 float(16, 32, 64, 128)
- 복소수 complex(64, 128, 256)
- 불리언 bool
- 문자열 string_
- 파이썬 오프젝트 object
- 유니코드 unicode_


## 관련함수들  

### 1. numpy정의하기, np.zeros(), np.ones(), np.arange() 함수


In [6]:
print(np.zeros(10))
print(np.zeros((3,5)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [7]:
print(np.ones(10))
print(np.ones((3,5)))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [9]:
print(np.arange(10))
print(np.arange(3,5))

[0 1 2 3 4 5 6 7 8 9]
[3 4]


### 2. Array 간 연산
#### 2-1. 크기가 같은 Array 간의 연산

- 기본적으로 numpy에서 연산을 할때는 크기가 서로 동일한 array 끼리 연산이 진행된다. 이때 같은 위치에 있는 요소들끼리 연산(element-wise operation)이 진행된다.

In [10]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[10,11,12],[13,14,15]])

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

[[11 13 15]
 [17 19 21]]
[[-9 -9 -9]
 [-9 -9 -9]]
[[10 22 36]
 [52 70 90]]
[[0.1        0.18181818 0.25      ]
 [0.30769231 0.35714286 0.4       ]]


#### 2-2. 크기가 다른 Array 간의 연산

- array의 브로드 캐스트
위에서는 array가 같은 크기를 가져야 서로 연산이 가능하다고 했지만, numpy에서는 브로드캐스트라는 기능을 제공한다.  
브로드캐스트란, 서로 크기가 다른 array가 연산이 가능하게끔 하는 것이다.


In [14]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr3 = np.array([10,11,12])

print(arr1)
print(arr3)
print()
print(arr1 + arr3)
print()
print(arr1 * 2)

[[1 2 3]
 [4 5 6]]
[10 11 12]

[[11 13 15]
 [14 16 18]]

[[ 2  4  6]
 [ 8 10 12]]


### 3. Array의 인덱싱
numpy에서 사용되는 인덱싱은 기본적으로 python 인덱싱과 동일하다.  
이때, python에서와 같이 1번째로 시작하는 것이 아니라 0번째로 시작하는 것에 주의한다.


In [15]:
arr1 = np.arange(10)

print(arr1[0])
print(arr1[3:9])
print(arr1[:])

0
[3 4 5 6 7 8]
[0 1 2 3 4 5 6 7 8 9]


In [16]:
arr2 = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12]])

#원소 하나꺼내기
print(arr2[0,0])

#2행의 모든 요소 꺼내기
print(arr2[2,:])

#3열의 모든 요소 꺼내기
print(arr2[:,3])

1
[ 9 10 11 12]
[ 4  8 12]


#### 3.1 Array Boolean 인덱싱(마스크)

위에서 이용한 다차원의 인덱싱을 응용하여 boolean 인덱싱을 할 수 있다.  
해당 기능은 주로 마스크라고 이야기하는데, boolean인덱싱을 통해 만들어낸 array를 통해 우리가 원하는 행 또는 열의 값만 뽑아낼 수 있다.  
즉, 마스크처럼 우리가 가리고 싶은 부분은 가리고, 원하는 요소만 꺼낼 수 있다.  


In [24]:
names = np.array(['Beomwoo','Beomwoo','Kim','Joan','Lee','Beomwoo','Park','Beomwoo'])
print(names.shape)

data = np.random.randn(8,4)
print(data.shape)
print(data)
print()

Beomwoo_mask = (names == 'Beomwoo')
print(Beomwoo_mask)
print(data[Beomwoo_mask,:])
print()
print(data[names == 'Kim',:])


(8,)
(8, 4)
[[-0.67215689  0.52413212 -0.66999699  0.49413172]
 [-0.55670206 -1.42098796  0.87207391  0.03984537]
 [-0.01370611  0.52074088  1.14740194 -0.63319189]
 [-0.74340928 -1.76600995  0.30630915  0.46822736]
 [-2.01310794 -0.04752401  1.21307918  1.30480317]
 [ 0.24956996 -0.42261799  1.29965414  0.54059366]
 [ 0.33427878 -1.29681638 -1.43521647 -0.00686931]
 [ 1.47396096 -1.31194472  0.17735138 -0.40103197]]

[ True  True False False False  True False  True]
[[-0.67215689  0.52413212 -0.66999699  0.49413172]
 [-0.55670206 -1.42098796  0.87207391  0.03984537]
 [ 0.24956996 -0.42261799  1.29965414  0.54059366]
 [ 1.47396096 -1.31194472  0.17735138 -0.40103197]]

[[-0.01370611  0.52074088  1.14740194 -0.63319189]]


In [26]:
# 논리 연산을 응용하여, 요소가 Kim 또는 Park인 행의 데이터만 꺼내기
print()
print(data[(names == 'Kim') | (names == 'Park'),:])


# 위에서 만든 마스크를 이용하여 0번째 열의 값이 0보다 작은 행을 구한다.
print()
print(data[data[:,0]<0,:])

# 0번째 열의 값이 0보다 작은 행의 2,3번째 열 값
print()
print(data[data[:,0]<0,2:4])

data[data[:,0]<0,2:4] = 0
print()
print(data)


[[-0.01370611  0.52074088  0.          0.        ]
 [ 0.33427878 -1.29681638 -1.43521647 -0.00686931]]

[[-0.67215689  0.52413212  0.          0.        ]
 [-0.55670206 -1.42098796  0.          0.        ]
 [-0.01370611  0.52074088  0.          0.        ]
 [-0.74340928 -1.76600995  0.          0.        ]
 [-2.01310794 -0.04752401  0.          0.        ]]

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

[[-0.67215689  0.52413212  0.          0.        ]
 [-0.55670206 -1.42098796  0.          0.        ]
 [-0.01370611  0.52074088  0.          0.        ]
 [-0.74340928 -1.76600995  0.          0.        ]
 [-2.01310794 -0.04752401  0.          0.        ]
 [ 0.24956996 -0.42261799  1.29965414  0.54059366]
 [ 0.33427878 -1.29681638 -1.43521647 -0.00686931]
 [ 1.47396096 -1.31194472  0.17735138 -0.40103197]]


### 4. Numpy 함수

#### 4-1. 하나의 array에 적용되는 함수


In [29]:
arr1 = np.random.randn(5,3)

# 각 성분의 절대값 계산하기
print(np.abs(arr1))
print()

# 각 성분의 제곱근 계산하기 ( == array ** 0.5)
print(np.sqrt(arr1))
print()

# 각 성분의 제곱 계산하기
print(np.square(arr1))
print()

# 각 성분을 무리수 e의 지수로 삼은 값을 계산하기
print(np.exp(arr1))
print()

# 각 성분을 자연로그, 상용로그, 밑이 2인 로그를 씌운 값을 계산하기
print(np.log(arr1))
print(np.log10(arr1))
print(np.log2(arr1))


[[1.21991695 1.1709667  0.47398415]
 [1.41422578 0.199344   0.71305801]
 [0.46942977 0.13088613 0.28344904]
 [0.51071172 0.71385086 0.7667436 ]
 [0.59606311 1.19398866 1.05423689]]

[[1.10449851 1.08211215        nan]
 [       nan        nan 0.84442762]
 [       nan        nan        nan]
 [0.71464097 0.84489695        nan]
 [       nan 1.09269788 1.02676039]]

[[1.48819736 1.37116301 0.22466098]
 [2.00003456 0.03973803 0.50845173]
 [0.22036431 0.01713118 0.08034336]
 [0.26082646 0.50958304 0.58789575]
 [0.35529123 1.42560891 1.11141543]]

[[3.38690643 3.22510884 0.62251712]
 [0.24311376 0.81926802 2.04022075]
 [0.62535877 0.87731767 0.7531815 ]
 [1.66647683 2.04183897 0.46452328]
 [0.55097651 3.30021843 2.86978437]]

[[ 0.19878278  0.15782965         nan]
 [        nan         nan -0.3381925 ]
 [        nan         nan         nan]
 [-0.67195001 -0.33708122         nan]
 [        nan  0.17729952  0.05281718]]
[[ 0.08633027  0.06854454         nan]
 [        nan         nan -0.14687514

C:\Users\Gene\Anaconda3\envs\torch\lib\site-packages\ipykernel_launcher.py:8: RuntimeWarning: invalid value encountered in sqrt
  
C:\Users\Gene\Anaconda3\envs\torch\lib\site-packages\ipykernel_launcher.py:20: RuntimeWarning: invalid value encountered in log
C:\Users\Gene\Anaconda3\envs\torch\lib\site-packages\ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in log10
C:\Users\Gene\Anaconda3\envs\torch\lib\site-packages\ipykernel_launcher.py:22: RuntimeWarning: invalid value encountered in log2


In [30]:
# 각 성분의 부호 계산하기(+인 경우 1, -인 경우 -1, 0인 경우 0)
print(np.sign(arr1))
print()

# 각 성분의 소수 첫 번째 자리에서 올림한 값을 계산하기
print(np.ceil(arr1))
print()

# 각 성분의 소수 첫 번째 자리에서 내림한 값을 계산하기
print(np.floor(arr1))
print()

# 각 성분이 NaN인 경우 True를, 아닌 경우 False를 반환하기
print(np.isnan(arr1))
print()

print(np.isnan(np.log(arr1)))
print()

# 각 성분이 무한대인 경우 True를, 아닌 경우 False를 반환하기
print(np.isinf(arr1))
print()
print(np.tanh(arr1))


[[ 1.  1. -1.]
 [-1. -1.  1.]
 [-1. -1. -1.]
 [ 1.  1. -1.]
 [-1.  1.  1.]]

[[ 2.  2. -0.]
 [-1. -0.  1.]
 [-0. -0. -0.]
 [ 1.  1. -0.]
 [-0.  2.  2.]]

[[ 1.  1. -1.]
 [-2. -1.  0.]
 [-1. -1. -1.]
 [ 0.  0. -1.]
 [-1.  1.  1.]]

[[False False False]
 [False False False]
 [False False False]
 [False False False]
 [False False False]]

[[False False  True]
 [ True  True False]
 [ True  True  True]
 [False False  True]
 [ True False False]]

[[False False False]
 [False False False]
 [False False False]
 [False False False]
 [False False False]]
[[ 0.83962968  0.82458182 -0.44141281]
 [-0.88838814 -0.19674479  0.61259085]
 [-0.43773846 -0.1301438  -0.27609424]
 [ 0.47049955  0.61308593 -0.64503192]
 [-0.53424224  0.83181181  0.78344812]]


C:\Users\Gene\Anaconda3\envs\torch\lib\site-packages\ipykernel_launcher.py:17: RuntimeWarning: invalid value encountered in log


#### 4-2. 두 개의 array에 적용되는 함수

In [37]:
arr1 = np.random.randn(5,3)
arr2 = np.random.randn(5,3)

print(arr1)
print()
print(arr2)

[[-0.577139   -0.49969064 -0.37993755]
 [-0.44003049  0.37499784  0.26138632]
 [-1.0336614   0.88722714  0.79108543]
 [ 1.15426937 -0.25679784 -0.72186218]
 [ 0.30560964 -0.58329677 -0.60258169]]

[[-0.07374794  1.84732943  1.78143016]
 [-0.82619579  0.11033179 -0.33125243]
 [ 0.6548585  -1.13841305  0.06764712]
 [-1.21319128  0.36324536 -0.88980688]
 [ 0.27302698  0.91835122  0.36475196]]


In [38]:
# 두 개의 array에 대해 동일한 위치의 성분끼리 연산 값을 계산하기(add, subtract, multiply, divide)
print(np.multiply(arr1,arr2))
print()

# 두 개의 array에 대해 동일한 위치의 성분끼리 비교하여 최대값 또는 최소값 계산하기(maximum, minimum)
print(np.maximum(arr1,arr2))
print()

# 두 개의 array에 대해 동일한 위치의 성분끼리 비교하여 최대값 또는 최소값 계산하기(maximum, minimum)
print(np.minimum(arr1,arr2))


[[ 0.04256281 -0.92309322 -0.67683221]
 [ 0.36355134  0.04137418 -0.08658485]
 [-0.67690195 -1.01003096  0.05351465]
 [-1.40034952 -0.09328062  0.64231793]
 [ 0.08343968 -0.5356713  -0.21979285]]

[[-0.07374794  1.84732943  1.78143016]
 [-0.44003049  0.37499784  0.26138632]
 [ 0.6548585   0.88722714  0.79108543]
 [ 1.15426937  0.36324536 -0.72186218]
 [ 0.30560964  0.91835122  0.36475196]]

[[-0.577139   -0.49969064 -0.37993755]
 [-0.82619579  0.11033179 -0.33125243]
 [-1.0336614  -1.13841305  0.06764712]
 [-1.21319128 -0.25679784 -0.88980688]
 [ 0.27302698 -0.58329677 -0.60258169]]


#### 4-3. 기초통계량 계산함수
통계 함수를 통해 array의 합이나 평균등을 구할 수 있고, axis라는 인자값으로 열 또는 행의 기초통계량 값을 구할 수 있다.

In [40]:
print(arr1)

# 전체 성분의 합을 계산
print(np.sum(arr1))

# 열 간의 합을 계산
print(np.sum(arr1, axis=1))

# 행 간의 합을 계산
print(np.sum(arr1, axis=0))


[[-0.577139   -0.49969064 -0.37993755]
 [-0.44003049  0.37499784  0.26138632]
 [-1.0336614   0.88722714  0.79108543]
 [ 1.15426937 -0.25679784 -0.72186218]
 [ 0.30560964 -0.58329677 -0.60258169]]
-1.3204218092260305
[-1.45676719  0.19635368  0.64465117  0.17560935 -0.88026882]
[-0.59095188 -0.07756026 -0.65190967]


In [41]:
print(arr1)

# 전체 성분의 평균을 계산
print(np.mean(arr1))

# 행 간의 평균을 계산
print(np.mean(arr1, axis=0))

# 열 간의 평균을 계산
print(np.mean(arr1, axis=1))

[[-0.577139   -0.49969064 -0.37993755]
 [-0.44003049  0.37499784  0.26138632]
 [-1.0336614   0.88722714  0.79108543]
 [ 1.15426937 -0.25679784 -0.72186218]
 [ 0.30560964 -0.58329677 -0.60258169]]
-0.08802812061506869
[-0.11819038 -0.01551205 -0.13038193]
[-0.48558906  0.06545123  0.21488372  0.05853645 -0.29342294]


In [49]:
print(arr1)

# 전체 성분의 표준편차, 분산, 최소값, 최대값 계산(std, var, min, max)
print(np.std(arr1))
print(np.var(arr1))
print()

#전체/열별 최솟값 산출
print(np.min(arr1))
print(np.min(arr1, axis=1))
print(np.argmin(arr1, axis=1))
print()

#전체/열별 최댓값 산출
print(np.max(arr1))
print(np.max(arr1, axis=1))
print(np.argmax(arr1, axis=1))

[[-0.577139   -0.49969064 -0.37993755]
 [-0.44003049  0.37499784  0.26138632]
 [-1.0336614   0.88722714  0.79108543]
 [ 1.15426937 -0.25679784 -0.72186218]
 [ 0.30560964 -0.58329677 -0.60258169]]
0.6434811820662267
0.4140680316733485

-1.0336613979620732
[-0.577139   -0.44003049 -1.0336614  -0.72186218 -0.60258169]
[0 0 0 2 2]

1.1542693653888547
[-0.37993755  0.37499784  0.88722714  1.15426937  0.30560964]
[2 1 1 0 0]


In [54]:
# 처음 성분부터 각 성분까지의 누적합을 계산
print(np.cumsum(arr1))
# 처음 성분부터 각 성분까지의 누적곱 계산
print(np.cumprod(arr1))
print()

print(np.cumsum(arr1,axis=1))
print(np.cumprod(arr1,axis=1))


[-0.577139   -1.07682964 -1.45676719 -1.89679768 -1.52179983 -1.26041351
 -2.29407491 -1.40684777 -0.61576234  0.53850702  0.28170918 -0.44015299
 -0.13454335 -0.71784012 -1.32042181]
[-5.77139002e-01  2.88390956e-01 -1.09570553e-01  4.82143839e-02
  1.80802900e-02  4.72594046e-03 -4.88502222e-03 -4.33412431e-03
 -3.42866258e-03 -3.95760018e-03  1.01630317e-03 -7.33630819e-04
 -2.24204650e-04  1.30777848e-04 -7.88043362e-05]

[[-0.577139   -1.07682964 -1.45676719]
 [-0.44003049 -0.06503264  0.19635368]
 [-1.0336614  -0.14643426  0.64465117]
 [ 1.15426937  0.89747153  0.17560935]
 [ 0.30560964 -0.27768713 -0.88026882]]
[[-0.577139    0.28839096 -0.10957055]
 [-0.44003049 -0.16501048 -0.04313148]
 [-1.0336614  -0.91709245 -0.72549847]
 [ 1.15426937 -0.29641388  0.21396997]
 [ 0.30560964 -0.17826112  0.10741688]]


#### 4-4. 정렬

In [73]:
arr1 = np.random.randn(3,2)
print(arr1)
print()

# 각 행의 열 성분에 대해서 오름차순으로 정렬
print(np.sort(arr1))
print()

# 각 행의 열 성분에 대해서 내림차순으로 정렬
print(np.sort(arr1)[::-1])
print()

# 각 열의 행 성분에 대해서 오름차순으로 정렬
print(np.sort(arr1,axis=0))
print()

# 각 열의 행 성분에 대해서 내림차순으로 정렬
print(np.sort(arr1,axis=0)[::-1])

[[ 1.24146341 -0.47670403]
 [ 0.31042226  1.35226698]
 [ 0.15357104 -0.22960201]]

[[-0.47670403  1.24146341]
 [ 0.31042226  1.35226698]
 [-0.22960201  0.15357104]]

[[-0.22960201  0.15357104]
 [ 0.31042226  1.35226698]
 [-0.47670403  1.24146341]]

[[ 0.15357104 -0.47670403]
 [ 0.31042226 -0.22960201]
 [ 1.24146341  1.35226698]]

[[ 1.24146341  1.35226698]
 [ 0.31042226 -0.22960201]
 [ 0.15357104 -0.47670403]]
